### ISSUE TITLE
How do you train a specific segmentation architecture with a particular backbone on a custom data set?

### ISSUE THREAD

**Issue by deshwalmahesh** [m-atarashi/Swin-Transformer-Semantic-Segmentation#1]
Hi,
If you have experience with this kind of things, can you update a minimal code for training a custom data set. For example if I want to train `SWIN-B` (or any other **SWIN** model) with `DeepLabv3+`  (or any other like `FPN` etc ) using `focal / dice` loss on a data set where I have **images -> masks**.  Just like your `demo.py` file, can you write something for training. That'd be helpful.

Also, when I pulled the `mmseg` repo to do that, I had lots of errors and `get_started.md` does not exist which had info about the training preparations of dataset.

**Comment by m-atarashi** [comment]
Hello. 
No sorry, I am new to machine learning and have no experience training on custom data or any advice to give you.

I hope your problem works out.
